theme: jekyll-theme-midnight
title: "Margaret Jagger, Student at CoW"
description: "A personal portfolio website"
url                      : "https://jmargaret2.github.io"
repository               : "jmargaret2/jmargaret2.github.io"
# Site Author
author:
  # name             : "Margaret Jagger"
  #avatar           : "/assets/images/profilePicture.JPG"
  bio              : "I'm a student at The College of Wooster, double majoring in Computer Science and Music"
  # location         : "Somewhere"
  # email            :
  links:
    - label: "Email"
      url: "mailto:margaretjagger2@gmail.com"
    - label: "GitHub"
      url: "https://github.com/jmargaret2"
    - label: "Linkedin"
      url: "https://linkedin.com/in/jmargaret2"
# Site Footer
footer:
  links:
    - label: "GitHub"
      # icon: "fab fa-fw fa-github"
      url: "https://github.com/jmargaret2"
github: [metadata]


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
krandowm:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo, rsquo, ldquo, rdquo
  enable_codearay: false

# Defaults
defaults:
  # _posts
    scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true