theme: jekyll-theme-midnight
title: "Margaret Jagger, Student at CoW"
subtitle: "Computer Science & Music Double Major, Statistical and Data Sciences Minor"
description: "A personal portfolio website"