theme: jekyll-theme-midnight
title: "Margaret Jagger, Student at CoW"
description: "A personal portfolio website"
github:
    zip_url: https://jmargaret2.github.io
url                      : "https://jmargaret2.github.io"
repository               : "jmargaret2/jmargaret2.github.io"